spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nom_de_ta_base
    username: votre_utilisateur
    password: votre_mot_de_passe
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082 